name: Project Pipeline

on:
    push:
      branches:
      - main
      paths:
      - project/**

#  Here, three jobs have been created, and their job_id values are job1_setup_environment, job2_build and job3_test.
jobs:
    job1_setup_environment:
        runs-on: ubuntu-latest
        steps:
            - run: echo The CI/CD is about to begin!
            # Checkout repository
            - name: Checkout
              uses: actions/checkout@v3
              with:
                path: main

            # Install python
            - name: Step#1- Setup Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            # Install dependencies
            - name: Step#2- Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                pip install requests
                echo "Environment is set up!"

            - name: Grant Access
              run: |
                chmod +x ../project/pipeline.sh
                chmod +x ./project/test.sh
                chmod +x ./project/pipeline.py
                chmod +x ./project/test.py
                chmod +x ./data/

    job2_build:
        runs-on: ubuntu-latest
        needs: job1_setup_environment

        steps:
            - name: Build python project/pipeline.sh
              run: | 
                echo The Build process about to begin!
                chmod +x ./project/pipeline.sh
                ./project/pipeline.sh
                echo "Build process completed!"

    job3_test:
        runs-on: ubuntu-latest
        needs: [job1_setup_environment, job2_build]

        steps:
            - run: echo The Testing process about to begin!
            - name: Build python project/test.sh
              run: | 
                chmod ./project/test.sh
                ./project/test.sh
                echo "Testing process completed!"
