name: Project Pipeline

on:
  push:
    branches:
      - main

jobs:


  job1_setup_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install requests
          echo "Environment is set up!"
  
  job2_build:
    runs-on: ubuntu-latest
    needs: [job1_setup_environment]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Build python project/pipeline.sh
        run: | 
          echo The Build process is about to begin!
          chmod u+r+x ./main/project/pipeline.sh
          cd ./main/project
          ./pipeline.sh
          echo "Build process completed!"

  job3_test:
    runs-on: ubuntu-latest
    needs: [job1_setup_environment, job2_build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - run: echo The Testing process is about to begin!

      - name: Build python project/test.sh
        run: | 
          chmod u+r+x ./main/project/test.sh
          cd ./main/project
          ./test.sh
          echo "Testing process completed!"
